language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
node_js:
  - '10'

addons:
  artifacts:
    s3_region: 'eu-central-1'

services:
  - postgresql
  - mysql
  - redis-server

before_install:
  - mysql -e 'create database test;'

install:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - npm install
  - php artisan key:generate
  - php artisan jwt:secret
  - php artisan migrate --seed
script:
  - # branches:
    #  only:
    #    - master
    #    - dev

notifications:
  email:
    recipients:
      - themaiby0@gmail.com
    on_failure: always
    on_success: never

