language: php
php:
  # - '7.1'
  # - '7.2'
  - '7.3'
node_js:
  - '10'

addons:
  artifacts:
    s3_region: 'eu-central-1'

services:
  - redis-server

before_install:
  - sudo apt remove mysql-server -y
  - wget -c https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get install mysql-server -y
  - mysql -e 'create database test;'

install:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - npm install
  - php artisan key:generate
  - php artisan jwt:secret -f
  - php artisan migrate --seed
  - npm run prod

after_success:
  - rm -rf node_modules/
  - rm -rf resources/js

# branches:
#  only:
#    - master
#    - dev

notifications:
  email:
    recipients:
      - themaiby0@gmail.com
    on_failure: always
    on_success: never

