language: php
php:
  - '7.3'
node_js:
  - '10'

services:
  - redis-server
  - postgresql

cache:
  directories:
    - vendor
    - node_modules

postgres:
  adapter: postgresql
  database: test
  username: postgres

before_install:
  - composer global require hirak/prestissimo
  - psql -c 'create database test;' -U postgres

install:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan jwt:secret -f
  - php artisan migrate --seed
  - npm install
  - npm run prod

after_success:
  - composer install --no-dev
  - rm -rf node_modules/
  - rm -rf resources/js/
  - rm -rf tests/
  - rm .env
  - rm .env.test
  - rm .babelrc
  - rm .editorconfig
  - rm .eslintrc.js
  - rm .gitattributes
  - rm .gitignore
  - rm .travis.yml
  - rm Vagrantfile
  - rm after.sh
  - rm aliases
  - rm composer.json
  - rm composer.lock
  - rm package-lock.json
  - rm package.json
  - rm phpunit.xml
  - rm tsconfig.json
  - rm webpack.mix.js
  - .git
  - cd ..
  - GZIP=-9 tar -C $TRAVIS_BUILD_DIR -zcvf $TRAVIS_BUILD_DIR-$TRAVIS_TAG.tar.gz --transform 's,^,${TRAVIS_TAG},S'
  - rm -rf $TRAVIS_BUILD_DIR

before_deploy:
  - ls -a

deploy:
  - provider: releases
    api_key: '$GITHUB_API'
    file: '$TRAVIS_BUILD_DIR-$TRAVIS_TAG.tar.gz'
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    recipients:
      - themaiby0@gmail.com
    on_failure: always
    on_success: never
