language: php
php:
  - '7.3'
node_js:
  - '10'

services:
  - redis-server
  - postgresql

cache:
  directories:
    - vendor
    - node_modules

postgres:
  adapter: postgresql
  database: test
  username: postgres

before_install:
  - composer global require hirak/prestissimo
  - psql -c 'create database test;' -U postgres

install:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan jwt:secret -f
  - php artisan migrate --seed
  - npm install
  - npm run prod

after_success:
  - ./makebuild.sh

deploy:
  - provider: releases
    api_key: '$GITHUB_API'
    file: '$TRAVIS_BUILD_DIR-$TRAVIS_TAG.tar.gz'
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    recipients:
      - themaiby0@gmail.com
    on_failure: always
    on_success: never
